#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFinal.Compile.Template.App.Code.Data
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class CookieManager : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\Template\App\Code\Data\CookieManager.cshtml"
           
    public NFinal.Compile.Template.App.Code.Data.CookieManagerModel Model { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral(@"//======================================================================
//
//        Copyright : Zhengzhou Strawberry Computer Technology Co.,LTD.
//        All rights reserved
//        
//        Application:NFinal MVC framework
//        Filename :CookieManager.cs
//        Description :Cookie管理类
//
//        created by Lucas at  2015-6-30`
//     
//        WebSite:http://www.nfinal.com
//
//======================================================================
using System;
using System.Collections.Generic;
using System.Web;

namespace ");

            
            #line 24 "..\..\Template\App\Code\Data\CookieManager.cshtml"
            
            
            #line default
            #line hidden
            
            #line 24 "..\..\Template\App\Code\Data\CookieManager.cshtml"
       Write(Model.project);

            
            #line default
            #line hidden
            
            #line 24 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                          
            
            #line default
            #line hidden
WriteLiteral(".");

            
            #line 24 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                              
            
            #line default
            #line hidden
            
            #line 24 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                         Write(Model.app);

            
            #line default
            #line hidden
            
            #line 24 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                        
            
            #line default
            #line hidden
WriteLiteral(@".Code.Data
{
    public class CookieManager:NFinal.Cookie
    {
		private CookieInfo _cookieInfo = new CookieInfo();
        public CookieManager()
        {
        }
        public CookieManager(NFinal.IAction action):base(action)
        {
            
        }
        public CookieManager(IDictionary<string, string> cookies):base(cookies)
        {

        }
");

            
            #line 40 "..\..\Template\App\Code\Data\CookieManager.cshtml"
        
            
            #line default
            #line hidden
            
            #line 40 "..\..\Template\App\Code\Data\CookieManager.cshtml"
         foreach(var declaraton in Model.declarations){

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("public ");

            
            #line 41 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                   
            
            #line default
            #line hidden
            
            #line 41 "..\..\Template\App\Code\Data\CookieManager.cshtml"
              Write(declaraton.typeName);

            
            #line default
            #line hidden
            
            #line 41 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                       
            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 41 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                           
            
            #line default
            #line hidden
            
            #line 41 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                      Write(declaraton.varName);

            
            #line default
            #line hidden
            
            #line 41 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                                              
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

WriteLiteral("{\r\n");

WriteLiteral("            ");

WriteLiteral("get\r\n");

WriteLiteral("            ");

WriteLiteral("{\r\n");

            
            #line 45 "..\..\Template\App\Code\Data\CookieManager.cshtml"
				if(declaraton.isString){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("_cookieInfo.");

            
            #line 46 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                     
            
            #line default
            #line hidden
            
            #line 46 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                Write(declaraton.varName);

            
            #line default
            #line hidden
            
            #line 46 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                        
            
            #line default
            #line hidden
WriteLiteral(" = this[\"");

            
            #line 46 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                                    
            
            #line default
            #line hidden
            
            #line 46 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                               Write(declaraton.varName);

            
            #line default
            #line hidden
            
            #line 46 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                                                       
            
            #line default
            #line hidden
WriteLiteral("\"];\r\n");

            
            #line 47 "..\..\Template\App\Code\Data\CookieManager.cshtml"
				}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

            
            #line 48 "..\..\Template\App\Code\Data\CookieManager.cshtml"
         
            
            #line default
            #line hidden
            
            #line 48 "..\..\Template\App\Code\Data\CookieManager.cshtml"
    Write(declaraton.typeName);

            
            #line default
            #line hidden
            
            #line 48 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                             
            
            #line default
            #line hidden
WriteLiteral(".TryParse(this[\"");

            
            #line 48 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 48 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                           Write(declaraton.varName);

            
            #line default
            #line hidden
            
            #line 48 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                                                   
            
            #line default
            #line hidden
WriteLiteral("\"],out _cookieInfo.");

            
            #line 48 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                                                                         
            
            #line default
            #line hidden
            
            #line 48 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                                                                    Write(declaraton.varName);

            
            #line default
            #line hidden
            
            #line 48 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                                                                                            
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

            
            #line 49 "..\..\Template\App\Code\Data\CookieManager.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t");

WriteLiteral("return _cookieInfo.");

            
            #line 50 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                           
            
            #line default
            #line hidden
            
            #line 50 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                      Write(declaraton.varName);

            
            #line default
            #line hidden
            
            #line 50 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

WriteLiteral("            ");

WriteLiteral("}\r\n");

WriteLiteral("            ");

WriteLiteral("set\r\n");

WriteLiteral("            ");

WriteLiteral("{\r\n");

WriteLiteral("                ");

WriteLiteral("_cookieInfo.");

            
            #line 54 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 54 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                           Write(declaraton.varName);

            
            #line default
            #line hidden
            
            #line 54 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                                   
            
            #line default
            #line hidden
WriteLiteral(" = value;\r\n");

            
            #line 55 "..\..\Template\App\Code\Data\CookieManager.cshtml"
				if(declaraton.isString){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("this[\"");

            
            #line 56 "..\..\Template\App\Code\Data\CookieManager.cshtml"
               
            
            #line default
            #line hidden
            
            #line 56 "..\..\Template\App\Code\Data\CookieManager.cshtml"
          Write(Model.cookiePrefix);

            
            #line default
            #line hidden
            
            #line 56 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 56 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                     
            
            #line default
            #line hidden
            
            #line 56 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                Write(declaraton.varName);

            
            #line default
            #line hidden
            
            #line 56 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                                        
            
            #line default
            #line hidden
WriteLiteral("\"]= value;\r\n");

            
            #line 57 "..\..\Template\App\Code\Data\CookieManager.cshtml"
				}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("this[\"");

            
            #line 58 "..\..\Template\App\Code\Data\CookieManager.cshtml"
               
            
            #line default
            #line hidden
            
            #line 58 "..\..\Template\App\Code\Data\CookieManager.cshtml"
          Write(Model.cookiePrefix);

            
            #line default
            #line hidden
            
            #line 58 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 58 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                     
            
            #line default
            #line hidden
            
            #line 58 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                Write(declaraton.varName);

            
            #line default
            #line hidden
            
            #line 58 "..\..\Template\App\Code\Data\CookieManager.cshtml"
                                                        
            
            #line default
            #line hidden
WriteLiteral("\"]= value.ToString();\r\n");

            
            #line 59 "..\..\Template\App\Code\Data\CookieManager.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("}\r\n");

WriteLiteral("        ");

WriteLiteral("}\r\n");

            
            #line 62 "..\..\Template\App\Code\Data\CookieManager.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    }\r\n}");

        }
    }
}
#pragma warning restore 1591
