#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFinal.Compile.SqlTemplate.postgresql
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Page : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\SqlTemplate\postgresql\Page.cshtml"
           
    public NFinal.Compile.SqlTemplate.Model.Page Model { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("#region\tvar ");

            
            #line 6 "..\..\SqlTemplate\postgresql\Page.cshtml"
              
            
            #line default
            #line hidden
            
            #line 6 "..\..\SqlTemplate\postgresql\Page.cshtml"
         Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 6 "..\..\SqlTemplate\postgresql\Page.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral(";分页\r\n\t\t\tvar __");

            
            #line 7 "..\..\SqlTemplate\postgresql\Page.cshtml"
           
            
            #line default
            #line hidden
            
            #line 7 "..\..\SqlTemplate\postgresql\Page.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 7 "..\..\SqlTemplate\postgresql\Page.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 7 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 7 "..\..\SqlTemplate\postgresql\Page.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 7 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_command__ = new Npgsql.NpgsqlCommand(\"");

            
            #line 7 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                          
            
            #line default
            #line hidden
            
            #line 7 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                     Write(Model.countSql);

            
            #line default
            #line hidden
            
            #line 7 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                         
            
            #line default
            #line hidden
WriteLiteral("\", ");

            
            #line 7 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                               
            
            #line default
            #line hidden
            
            #line 7 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                          Write(Model.connectionVarName);

            
            #line default
            #line hidden
            
            #line 7 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                       
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

            
            #line 8 "..\..\SqlTemplate\postgresql\Page.cshtml"
			
            
            #line default
            #line hidden
            
            #line 8 "..\..\SqlTemplate\postgresql\Page.cshtml"
    if(Model.isTransaction){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 9 "..\..\SqlTemplate\postgresql\Page.cshtml"
         
            
            #line default
            #line hidden
            
            #line 9 "..\..\SqlTemplate\postgresql\Page.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 9 "..\..\SqlTemplate\postgresql\Page.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 9 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 9 "..\..\SqlTemplate\postgresql\Page.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 9 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_command__.Transaction=");

            
            #line 9 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                        
            
            #line default
            #line hidden
            
            #line 9 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                   Write(Model.transactionVarName);

            
            #line default
            #line hidden
            
            #line 9 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                 
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

            
            #line 10 "..\..\SqlTemplate\postgresql\Page.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 11 "..\..\SqlTemplate\postgresql\Page.cshtml"
    if(Model.sqlVarParameters.Count>0){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("var __");

            
            #line 12 "..\..\SqlTemplate\postgresql\Page.cshtml"
             
            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\postgresql\Page.cshtml"
        Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 12 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\postgresql\Page.cshtml"
                               Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                  
            
            #line default
            #line hidden
WriteLiteral("_parameters__=new Npgsql.NpgsqlParameter[");

            
            #line 12 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                              
            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                         Write(Model.sqlVarParameters.Count);

            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                           
            
            #line default
            #line hidden
WriteLiteral("];\r\n");

            
            #line 13 "..\..\SqlTemplate\postgresql\Page.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 14 "..\..\SqlTemplate\postgresql\Page.cshtml"
     int i=0;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 15 "..\..\SqlTemplate\postgresql\Page.cshtml"
			
            
            #line default
            #line hidden
            
            #line 15 "..\..\SqlTemplate\postgresql\Page.cshtml"
    foreach(var sqlVarParameter in Model.sqlVarParameters){
			if(sqlVarParameter.field.length>0){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
         
            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                        Write(i);

            
            #line default
            #line hidden
WriteLiteral("] = new Npgsql.NpgsqlParameter(\"");

WriteLiteral("@");

            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                   
            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                              Write(sqlVarParameter.name);

            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                        
            
            #line default
            #line hidden
WriteLiteral("\",NpgsqlTypes.NpgsqlDbType.");

            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                      
            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                 Write(sqlVarParameter.field.dbType);

            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                   
            
            #line default
            #line hidden
WriteLiteral(",");

            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                       
            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                  Write(sqlVarParameter.field.length);

            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                    
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 18 "..\..\SqlTemplate\postgresql\Page.cshtml"
         
            
            #line default
            #line hidden
            
            #line 18 "..\..\SqlTemplate\postgresql\Page.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 18 "..\..\SqlTemplate\postgresql\Page.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 18 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 18 "..\..\SqlTemplate\postgresql\Page.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 18 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 18 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                        Write(i);

            
            #line default
            #line hidden
WriteLiteral("].Value = ");

            
            #line 18 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                           
            
            #line default
            #line hidden
            
            #line 18 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                      Write(sqlVarParameter.csharpName);

            
            #line default
            #line hidden
            
            #line 18 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                      
            
            #line default
            #line hidden
WriteLiteral(".WithDBNull();\r\n");

            
            #line 19 "..\..\SqlTemplate\postgresql\Page.cshtml"
			}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
         
            
            #line default
            #line hidden
            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                        Write(i);

            
            #line default
            #line hidden
WriteLiteral("] = new Npgsql.NpgsqlParameter(\"");

WriteLiteral("@");

            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                   
            
            #line default
            #line hidden
            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                              Write(sqlVarParameter.name);

            
            #line default
            #line hidden
            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                        
            
            #line default
            #line hidden
WriteLiteral("\",NpgsqlTypes.NpgsqlDbType.");

            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                      
            
            #line default
            #line hidden
            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                 Write(sqlVarParameter.field.dbType);

            
            #line default
            #line hidden
            
            #line 20 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                   
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 21 "..\..\SqlTemplate\postgresql\Page.cshtml"
         
            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\postgresql\Page.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\postgresql\Page.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 21 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\postgresql\Page.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 21 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                        Write(i);

            
            #line default
            #line hidden
WriteLiteral("].Value = ");

            
            #line 21 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                           
            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                      Write(sqlVarParameter.csharpName);

            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                      
            
            #line default
            #line hidden
WriteLiteral(".WithDBNull();\r\n");

            
            #line 22 "..\..\SqlTemplate\postgresql\Page.cshtml"
			}
			i++;
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 25 "..\..\SqlTemplate\postgresql\Page.cshtml"
    if(Model.sqlVarParameters.Count>0){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 26 "..\..\SqlTemplate\postgresql\Page.cshtml"
         
            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\postgresql\Page.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\postgresql\Page.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 26 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\postgresql\Page.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_command__.Parameters.AddRange(__");

            
            #line 26 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                  
            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                             Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                     
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 26 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                         
            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                    Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                       
            
            #line default
            #line hidden
WriteLiteral("_parameters__);\r\n");

            
            #line 27 "..\..\SqlTemplate\postgresql\Page.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 28 "..\..\SqlTemplate\postgresql\Page.cshtml"
     
            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\postgresql\Page.cshtml"
Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\postgresql\Page.cshtml"
                       
            
            #line default
            #line hidden
WriteLiteral(".recordCount =__");

            
            #line 28 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                          
            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                     Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                             
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 28 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                 
            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                            Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                               
            
            #line default
            #line hidden
WriteLiteral("_command__.ExecuteScalar().AsVar();\r\n\t\t\t__");

            
            #line 29 "..\..\SqlTemplate\postgresql\Page.cshtml"
       
            
            #line default
            #line hidden
            
            #line 29 "..\..\SqlTemplate\postgresql\Page.cshtml"
  Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 29 "..\..\SqlTemplate\postgresql\Page.cshtml"
                          
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 29 "..\..\SqlTemplate\postgresql\Page.cshtml"
                              
            
            #line default
            #line hidden
            
            #line 29 "..\..\SqlTemplate\postgresql\Page.cshtml"
                         Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 29 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral("_command__.Dispose();\r\n");

            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
			
            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
     
            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                       
            
            #line default
            #line hidden
WriteLiteral(".count = (");

            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                               Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                      
            
            #line default
            #line hidden
WriteLiteral(".recordCount % ");

            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                        
            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                   Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                          
            
            #line default
            #line hidden
WriteLiteral(".size==0)? ");

            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                        
            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                   Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                          
            
            #line default
            #line hidden
WriteLiteral(".recordCount/");

            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                          
            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                     Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                            
            
            #line default
            #line hidden
WriteLiteral(".size:");

            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                     
            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                       
            
            #line default
            #line hidden
WriteLiteral(".recordCount/");

            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                       
            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                  Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                         
            
            #line default
            #line hidden
WriteLiteral(".size+1;\r\n\t\t\t//传页码时用的变量名\r\n\t\t\tif (");

            
            #line 32 "..\..\SqlTemplate\postgresql\Page.cshtml"
         
            
            #line default
            #line hidden
            
            #line 32 "..\..\SqlTemplate\postgresql\Page.cshtml"
    Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 32 "..\..\SqlTemplate\postgresql\Page.cshtml"
                           
            
            #line default
            #line hidden
WriteLiteral(".index > ");

            
            #line 32 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                       
            
            #line default
            #line hidden
            
            #line 32 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                  Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 32 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                         
            
            #line default
            #line hidden
WriteLiteral(".count)\r\n            {\r\n");

            
            #line 34 "..\..\SqlTemplate\postgresql\Page.cshtml"
                
            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\postgresql\Page.cshtml"
                  
            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\postgresql\Page.cshtml"
             Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                    
            
            #line default
            #line hidden
WriteLiteral(".index = ");

            
            #line 34 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                           Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                  
            
            #line default
            #line hidden
WriteLiteral(".count;\r\n            }\r\n            if (");

            
            #line 36 "..\..\SqlTemplate\postgresql\Page.cshtml"
                  
            
            #line default
            #line hidden
            
            #line 36 "..\..\SqlTemplate\postgresql\Page.cshtml"
             Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 36 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                    
            
            #line default
            #line hidden
WriteLiteral(".index < 1)\r\n            {\r\n                ");

            
            #line 38 "..\..\SqlTemplate\postgresql\Page.cshtml"
                  
            
            #line default
            #line hidden
            
            #line 38 "..\..\SqlTemplate\postgresql\Page.cshtml"
             Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 38 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                    
            
            #line default
            #line hidden
WriteLiteral(".index = 1;\r\n            }\r\n");

            
            #line 40 "..\..\SqlTemplate\postgresql\Page.cshtml"
			
            
            #line default
            #line hidden
            
            #line 40 "..\..\SqlTemplate\postgresql\Page.cshtml"
    if(Model.hasGenericType){
			if(Model.isDeclaration){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("List<");

            
            #line 42 "..\..\SqlTemplate\postgresql\Page.cshtml"
            
            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\postgresql\Page.cshtml"
       Write(Model.type);

            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\postgresql\Page.cshtml"
                       
            
            #line default
            #line hidden
WriteLiteral("> ");

            
            #line 42 "..\..\SqlTemplate\postgresql\Page.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\postgresql\Page.cshtml"
                       Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                          
            
            #line default
            #line hidden
WriteLiteral("=new List<");

            
            #line 42 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                       
            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                  Write(Model.type);

            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                  
            
            #line default
            #line hidden
WriteLiteral(">();\r\n");

            
            #line 43 "..\..\SqlTemplate\postgresql\Page.cshtml"
			}
			}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("var ");

            
            #line 45 "..\..\SqlTemplate\postgresql\Page.cshtml"
           
            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\postgresql\Page.cshtml"
      Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\postgresql\Page.cshtml"
                         
            
            #line default
            #line hidden
WriteLiteral(" = new List<__");

            
            #line 45 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                          
            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                     Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                             
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 45 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                 
            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                            Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                               
            
            #line default
            #line hidden
WriteLiteral("__>();\r\n");

            
            #line 46 "..\..\SqlTemplate\postgresql\Page.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            //计算得到SQL语句\r\n\t\t\t__@{@Model.functionName}_@{@Model.varName}_command__ " +
"= new Npgsql.NpgsqlCommand(string.Format(\"");

            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                    
            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                               Write(Model.pageSql);

            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                  
            
            #line default
            #line hidden
WriteLiteral("\",");

            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                       
            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                  Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                         
            
            #line default
            #line hidden
WriteLiteral(".size,(");

            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                   
            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                              Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                     
            
            #line default
            #line hidden
WriteLiteral(".index-1)*");

            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                  
            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                             Write(Model.pageVarName);

            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                    
            
            #line default
            #line hidden
WriteLiteral(".size), ");

            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                               
            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                          Write(Model.connectionVarName);

            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                       
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

            
            #line 49 "..\..\SqlTemplate\postgresql\Page.cshtml"
			
            
            #line default
            #line hidden
            
            #line 49 "..\..\SqlTemplate\postgresql\Page.cshtml"
    if(Model.isTransaction){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 50 "..\..\SqlTemplate\postgresql\Page.cshtml"
         
            
            #line default
            #line hidden
            
            #line 50 "..\..\SqlTemplate\postgresql\Page.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 50 "..\..\SqlTemplate\postgresql\Page.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 50 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 50 "..\..\SqlTemplate\postgresql\Page.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 50 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_command__.Transaction=");

            
            #line 50 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                        
            
            #line default
            #line hidden
            
            #line 50 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                   Write(Model.transactionVarName);

            
            #line default
            #line hidden
            
            #line 50 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                 
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

            
            #line 51 "..\..\SqlTemplate\postgresql\Page.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 52 "..\..\SqlTemplate\postgresql\Page.cshtml"
    if(Model.sqlVarParameters.Count>0){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 53 "..\..\SqlTemplate\postgresql\Page.cshtml"
         
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\postgresql\Page.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\postgresql\Page.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 53 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\postgresql\Page.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_command__.Parameters.AddRange(__");

            
            #line 53 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                  
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                             Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                     
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 53 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                         
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                    Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                       
            
            #line default
            #line hidden
WriteLiteral("_parameters__);\r\n");

            
            #line 54 "..\..\SqlTemplate\postgresql\Page.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\tvar __");

            
            #line 55 "..\..\SqlTemplate\postgresql\Page.cshtml"
           
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\postgresql\Page.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\postgresql\Page.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 55 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\postgresql\Page.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_reader__= __");

            
            #line 55 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                           Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                   
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 55 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                       
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                  Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                     
            
            #line default
            #line hidden
WriteLiteral("_command__.ExecuteReader();\r\n\t\t\tif (__");

            
            #line 56 "..\..\SqlTemplate\postgresql\Page.cshtml"
           
            
            #line default
            #line hidden
            
            #line 56 "..\..\SqlTemplate\postgresql\Page.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 56 "..\..\SqlTemplate\postgresql\Page.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 56 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 56 "..\..\SqlTemplate\postgresql\Page.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 56 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_reader__.HasRows)\r\n\t\t\t{\r\n\t\t\t\twhile (__");

            
            #line 58 "..\..\SqlTemplate\postgresql\Page.cshtml"
               
            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\postgresql\Page.cshtml"
          Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                  
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 58 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                      
            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                 Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                    
            
            #line default
            #line hidden
WriteLiteral("_reader__.Read())\r\n\t\t\t\t{\r\n");

            
            #line 60 "..\..\SqlTemplate\postgresql\Page.cshtml"
					
            
            #line default
            #line hidden
            
            #line 60 "..\..\SqlTemplate\postgresql\Page.cshtml"
      if(Model.hasGenericType){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("var __");

            
            #line 61 "..\..\SqlTemplate\postgresql\Page.cshtml"
               
            
            #line default
            #line hidden
            
            #line 61 "..\..\SqlTemplate\postgresql\Page.cshtml"
          Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 61 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                  
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 61 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                      
            
            #line default
            #line hidden
            
            #line 61 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                 Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 61 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                    
            
            #line default
            #line hidden
WriteLiteral("_temp__ = new ");

            
            #line 61 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                     
            
            #line default
            #line hidden
            
            #line 61 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                Write(Model.type);

            
            #line default
            #line hidden
            
            #line 61 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                
            
            #line default
            #line hidden
WriteLiteral("();\r\n");

            
            #line 62 "..\..\SqlTemplate\postgresql\Page.cshtml"
					}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("var __");

            
            #line 63 "..\..\SqlTemplate\postgresql\Page.cshtml"
               
            
            #line default
            #line hidden
            
            #line 63 "..\..\SqlTemplate\postgresql\Page.cshtml"
          Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 63 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                  
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 63 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                      
            
            #line default
            #line hidden
            
            #line 63 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                 Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 63 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                    
            
            #line default
            #line hidden
WriteLiteral("_temp__ = new __");

            
            #line 63 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                       
            
            #line default
            #line hidden
            
            #line 63 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                  Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 63 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                          
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 63 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                              
            
            #line default
            #line hidden
            
            #line 63 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                         Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 63 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                            
            
            #line default
            #line hidden
WriteLiteral("__();\r\n");

            
            #line 64 "..\..\SqlTemplate\postgresql\Page.cshtml"
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

            
            #line 65 "..\..\SqlTemplate\postgresql\Page.cshtml"
       i=0;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 66 "..\..\SqlTemplate\postgresql\Page.cshtml"
					
            
            #line default
            #line hidden
            
            #line 66 "..\..\SqlTemplate\postgresql\Page.cshtml"
      foreach(var field in Model.fields){
					if(field.allowNull){
					if(field.isValueType){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("if(!__");

            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
               
            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
          Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                  
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                      
            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                 Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                    
            
            #line default
            #line hidden
WriteLiteral("_reader__.IsDBNull(");

            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                   Write(i);

            
            #line default
            #line hidden
WriteLiteral(")){__");

            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                 
            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                            Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                    
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                        
            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                   Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                      
            
            #line default
            #line hidden
WriteLiteral("_temp__.");

            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                 
            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                            Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                       
            
            #line default
            #line hidden
WriteLiteral(" =");

            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                            
            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                       Write(field.GetMethodConvert);

            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                   
            
            #line default
            #line hidden
WriteLiteral(" __");

            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                         
            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                
            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                              
            
            #line default
            #line hidden
WriteLiteral("_reader__.");

            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                           
            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                      Write(field.GetMethodName);

            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                                               
            
            #line default
            #line hidden
WriteLiteral("(");

            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                                            Write(i);

            
            #line default
            #line hidden
WriteLiteral(")");

            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                                                      
            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                                                 Write(field.GetMethodValue);

            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                                                                           
            
            #line default
            #line hidden
WriteLiteral(";}\r\n");

            
            #line 70 "..\..\SqlTemplate\postgresql\Page.cshtml"
					}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("__");

            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
           
            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_temp__.");

            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                           
            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                      Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                 
            
            #line default
            #line hidden
WriteLiteral(" =__");

            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                        
            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                   Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                           
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                               
            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                          Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                             
            
            #line default
            #line hidden
WriteLiteral("_reader__.IsDBNull(");

            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                            Write(i);

            
            #line default
            #line hidden
WriteLiteral(")?null:");

            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                            
            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                       Write(field.GetMethodConvert);

            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                   
            
            #line default
            #line hidden
WriteLiteral(" __");

            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                         
            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                
            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                              
            
            #line default
            #line hidden
WriteLiteral("_reader__.");

            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                           
            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                      Write(field.GetMethodName);

            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                                               
            
            #line default
            #line hidden
WriteLiteral("(");

            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                                            Write(i);

            
            #line default
            #line hidden
WriteLiteral(")");

            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                                                      
            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                                                 Write(field.GetMethodValue);

            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                                                                                           
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

            
            #line 72 "..\..\SqlTemplate\postgresql\Page.cshtml"
					}
					}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("__");

            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
           
            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_temp__.");

            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                           
            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                      Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                 
            
            #line default
            #line hidden
WriteLiteral(" =");

            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                      
            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                 Write(field.GetMethodConvert);

            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                             
            
            #line default
            #line hidden
WriteLiteral(" __");

            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                   
            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                              Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                      
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                          
            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                     Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                        
            
            #line default
            #line hidden
WriteLiteral("_reader__.");

            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                     
            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                Write(field.GetMethodName);

            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                         
            
            #line default
            #line hidden
WriteLiteral("(");

            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                      Write(i);

            
            #line default
            #line hidden
WriteLiteral(")");

            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                
            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                           Write(field.GetMethodValue);

            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                                                                                                                                                                     
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

            
            #line 75 "..\..\SqlTemplate\postgresql\Page.cshtml"
					}
					i++;
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

            
            #line 78 "..\..\SqlTemplate\postgresql\Page.cshtml"
       
            
            #line default
            #line hidden
            
            #line 78 "..\..\SqlTemplate\postgresql\Page.cshtml"
  Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 78 "..\..\SqlTemplate\postgresql\Page.cshtml"
                     
            
            #line default
            #line hidden
WriteLiteral(".Add(__");

            
            #line 78 "..\..\SqlTemplate\postgresql\Page.cshtml"
                               
            
            #line default
            #line hidden
            
            #line 78 "..\..\SqlTemplate\postgresql\Page.cshtml"
                          Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 78 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                  
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 78 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                      
            
            #line default
            #line hidden
            
            #line 78 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                 Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 78 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                                                    
            
            #line default
            #line hidden
WriteLiteral("_temp__);\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\t__");

            
            #line 81 "..\..\SqlTemplate\postgresql\Page.cshtml"
       
            
            #line default
            #line hidden
            
            #line 81 "..\..\SqlTemplate\postgresql\Page.cshtml"
  Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 81 "..\..\SqlTemplate\postgresql\Page.cshtml"
                          
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 81 "..\..\SqlTemplate\postgresql\Page.cshtml"
                              
            
            #line default
            #line hidden
            
            #line 81 "..\..\SqlTemplate\postgresql\Page.cshtml"
                         Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 81 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral("_reader__.Dispose();\r\n\t\t\t__");

            
            #line 82 "..\..\SqlTemplate\postgresql\Page.cshtml"
       
            
            #line default
            #line hidden
            
            #line 82 "..\..\SqlTemplate\postgresql\Page.cshtml"
  Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 82 "..\..\SqlTemplate\postgresql\Page.cshtml"
                          
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 82 "..\..\SqlTemplate\postgresql\Page.cshtml"
                              
            
            #line default
            #line hidden
            
            #line 82 "..\..\SqlTemplate\postgresql\Page.cshtml"
                         Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 82 "..\..\SqlTemplate\postgresql\Page.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral("_command__.Dispose();\r\n\t\t\t#endregion\r\n\t\t\t");

        }
    }
}
#pragma warning restore 1591
