;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2015/6/4 7:41:23

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; 1.前言 1.入门\1.前言.html
#define IDH_1001	1001	; 2.简介,为什么要用NFinal 1.入门\2.简介,为什么要用NFinal.html
#define IDH_1002	1002	; 3.如何下载 1.入门\3.如何下载.html
#define IDH_1003	1003	; 4.安装,还有更简单的吗 1.入门\4.安装,还有更简单的吗.html
