#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFinal.Compile.SqlTemplate.oracle
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Insert : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\SqlTemplate\oracle\Insert.cshtml"
           
    public NFinal.Compile.SqlTemplate.Model.Insert Model { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("#region\tvar ");

            
            #line 6 "..\..\SqlTemplate\oracle\Insert.cshtml"
              
            
            #line default
            #line hidden
            
            #line 6 "..\..\SqlTemplate\oracle\Insert.cshtml"
         Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 6 "..\..\SqlTemplate\oracle\Insert.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("; 插入并返回ID\r\n\t\t\tif(Model.isDeclaration){\r\n\t\t\t\tvar ");

            
            #line 8 "..\..\SqlTemplate\oracle\Insert.cshtml"
          
            
            #line default
            #line hidden
            
            #line 8 "..\..\SqlTemplate\oracle\Insert.cshtml"
     Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 8 "..\..\SqlTemplate\oracle\Insert.cshtml"
                        
            
            #line default
            #line hidden
WriteLiteral("=0;\r\n\t\t\t}\r\n\t\t\tvar __");

            
            #line 10 "..\..\SqlTemplate\oracle\Insert.cshtml"
           
            
            #line default
            #line hidden
            
            #line 10 "..\..\SqlTemplate\oracle\Insert.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 10 "..\..\SqlTemplate\oracle\Insert.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 10 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 10 "..\..\SqlTemplate\oracle\Insert.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 10 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_NonQuery = 0;\r\n\t\t\tvar __");

            
            #line 11 "..\..\SqlTemplate\oracle\Insert.cshtml"
           
            
            #line default
            #line hidden
            
            #line 11 "..\..\SqlTemplate\oracle\Insert.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 11 "..\..\SqlTemplate\oracle\Insert.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 11 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 11 "..\..\SqlTemplate\oracle\Insert.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 11 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_command__ = new Oracle.ManagedDataAccess.Client.OracleCommand(\"");

            
            #line 11 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                   
            
            #line default
            #line hidden
            
            #line 11 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                              Write(Model.sql);

            
            #line default
            #line hidden
            
            #line 11 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                             
            
            #line default
            #line hidden
WriteLiteral("\", ");

            
            #line 11 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                   
            
            #line default
            #line hidden
            
            #line 11 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                              Write(Model.connectionVarName);

            
            #line default
            #line hidden
            
            #line 11 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                           
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

            
            #line 12 "..\..\SqlTemplate\oracle\Insert.cshtml"
			
            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\oracle\Insert.cshtml"
    if(Model.isTransaction){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 13 "..\..\SqlTemplate\oracle\Insert.cshtml"
         
            
            #line default
            #line hidden
            
            #line 13 "..\..\SqlTemplate\oracle\Insert.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 13 "..\..\SqlTemplate\oracle\Insert.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 13 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 13 "..\..\SqlTemplate\oracle\Insert.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 13 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_command__.Transaction=");

            
            #line 13 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                        
            
            #line default
            #line hidden
            
            #line 13 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                   Write(Model.transactionVarName);

            
            #line default
            #line hidden
            
            #line 13 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                 
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

            
            #line 14 "..\..\SqlTemplate\oracle\Insert.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 15 "..\..\SqlTemplate\oracle\Insert.cshtml"
    if(Model.sqlVarParameters.Count>0){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("var __");

            
            #line 16 "..\..\SqlTemplate\oracle\Insert.cshtml"
             
            
            #line default
            #line hidden
            
            #line 16 "..\..\SqlTemplate\oracle\Insert.cshtml"
        Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 16 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 16 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 16 "..\..\SqlTemplate\oracle\Insert.cshtml"
                               Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 16 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                  
            
            #line default
            #line hidden
WriteLiteral("_parameters__=new Oracle.ManagedDataAccess.Client.OracleParameter[");

            
            #line 16 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                       
            
            #line default
            #line hidden
            
            #line 16 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                  Write(Model.sqlVarParameters.Count);

            
            #line default
            #line hidden
            
            #line 16 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                    
            
            #line default
            #line hidden
WriteLiteral("];\r\n");

            
            #line 17 "..\..\SqlTemplate\oracle\Insert.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 18 "..\..\SqlTemplate\oracle\Insert.cshtml"
     int i=0;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 19 "..\..\SqlTemplate\oracle\Insert.cshtml"
			
            
            #line default
            #line hidden
            
            #line 19 "..\..\SqlTemplate\oracle\Insert.cshtml"
    foreach(var sqlVarParameter in Model.sqlVarParameters){
			if(sqlVarParameter.field.length>0){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
         
            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                        Write(i);

            
            #line default
            #line hidden
WriteLiteral("] = new Oracle.ManagedDataAccess.Client.OracleParameter(\":");

            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                           
            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                      Write(sqlVarParameter.name);

            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                
            
            #line default
            #line hidden
WriteLiteral("\",Oracle.ManagedDataAccess.Client.OracleDbType.");

            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                                                                  
            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                                                             Write(sqlVarParameter.field.dbType);

            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                                                                                               
            
            #line default
            #line hidden
WriteLiteral(",");

            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                                                                                                   
            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                                                                                              Write(sqlVarParameter.field.length);

            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                                                                                                                                
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 22 "..\..\SqlTemplate\oracle\Insert.cshtml"
         
            
            #line default
            #line hidden
            
            #line 22 "..\..\SqlTemplate\oracle\Insert.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 22 "..\..\SqlTemplate\oracle\Insert.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 22 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 22 "..\..\SqlTemplate\oracle\Insert.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 22 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 22 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                        Write(i);

            
            #line default
            #line hidden
WriteLiteral("].Value = ");

            
            #line 22 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                           
            
            #line default
            #line hidden
            
            #line 22 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                      Write(sqlVarParameter.csharpName);

            
            #line default
            #line hidden
            
            #line 22 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                      
            
            #line default
            #line hidden
WriteLiteral(".WithDBNull();\r\n");

            
            #line 23 "..\..\SqlTemplate\oracle\Insert.cshtml"
			}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
         
            
            #line default
            #line hidden
            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                        Write(i);

            
            #line default
            #line hidden
WriteLiteral("] = new Oracle.ManagedDataAccess.Client.OracleParameter(\":");

            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                           
            
            #line default
            #line hidden
            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                      Write(sqlVarParameter.name);

            
            #line default
            #line hidden
            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                
            
            #line default
            #line hidden
WriteLiteral("\",Oracle.ManagedDataAccess.Client.OracleDbType.");

            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                                                                  
            
            #line default
            #line hidden
            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                                                             Write(sqlVarParameter.field.dbType);

            
            #line default
            #line hidden
            
            #line 24 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                                                                                               
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 25 "..\..\SqlTemplate\oracle\Insert.cshtml"
         
            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\oracle\Insert.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\oracle\Insert.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 25 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\oracle\Insert.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 25 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                        Write(i);

            
            #line default
            #line hidden
WriteLiteral("].Value = ");

            
            #line 25 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                           
            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                      Write(sqlVarParameter.csharpName);

            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                      
            
            #line default
            #line hidden
WriteLiteral(".WithDBNull();\r\n");

            
            #line 26 "..\..\SqlTemplate\oracle\Insert.cshtml"
			}
			i++;
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 29 "..\..\SqlTemplate\oracle\Insert.cshtml"
    if(Model.sqlVarParameters.Count>0){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 30 "..\..\SqlTemplate\oracle\Insert.cshtml"
         
            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\oracle\Insert.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\oracle\Insert.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 30 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\oracle\Insert.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_command__.Parameters.AddRange(__");

            
            #line 30 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                  
            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                             Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                     
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 30 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                         
            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                    Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 30 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                       
            
            #line default
            #line hidden
WriteLiteral("_parameters__);\r\n");

            
            #line 31 "..\..\SqlTemplate\oracle\Insert.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\ttry\r\n\t\t\t{\r\n\t\t\t\t__");

            
            #line 34 "..\..\SqlTemplate\oracle\Insert.cshtml"
        
            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\oracle\Insert.cshtml"
   Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\oracle\Insert.cshtml"
                           
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 34 "..\..\SqlTemplate\oracle\Insert.cshtml"
                               
            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\oracle\Insert.cshtml"
                          Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                             
            
            #line default
            #line hidden
WriteLiteral("_NonQuery = __");

            
            #line 34 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                              
            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                         Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                 
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 34 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                     
            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 34 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                   
            
            #line default
            #line hidden
WriteLiteral("_command__.ExecuteNonQuery();\r\n\t\t\t\t__");

            
            #line 35 "..\..\SqlTemplate\oracle\Insert.cshtml"
        
            
            #line default
            #line hidden
            
            #line 35 "..\..\SqlTemplate\oracle\Insert.cshtml"
   Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 35 "..\..\SqlTemplate\oracle\Insert.cshtml"
                           
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 35 "..\..\SqlTemplate\oracle\Insert.cshtml"
                               
            
            #line default
            #line hidden
            
            #line 35 "..\..\SqlTemplate\oracle\Insert.cshtml"
                          Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 35 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                             
            
            #line default
            #line hidden
WriteLiteral("_command__.Dispose();\r\n\t\t\t\tif(__");

            
            #line 36 "..\..\SqlTemplate\oracle\Insert.cshtml"
           
            
            #line default
            #line hidden
            
            #line 36 "..\..\SqlTemplate\oracle\Insert.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 36 "..\..\SqlTemplate\oracle\Insert.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 36 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 36 "..\..\SqlTemplate\oracle\Insert.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 36 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_NonQuery>0)\r\n\t\t\t\t{\r\n\t\t\t\t\t__");

            
            #line 38 "..\..\SqlTemplate\oracle\Insert.cshtml"
         
            
            #line default
            #line hidden
            
            #line 38 "..\..\SqlTemplate\oracle\Insert.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 38 "..\..\SqlTemplate\oracle\Insert.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 38 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 38 "..\..\SqlTemplate\oracle\Insert.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 38 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_command__ = new Oracle.ManagedDataAccess.Client.OracleCommand(\"select ");

            
            #line 38 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                        
            
            #line default
            #line hidden
            
            #line 38 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                   Write(Model.tableName);

            
            #line default
            #line hidden
            
            #line 38 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                        
            
            #line default
            #line hidden
WriteLiteral("_id_sequence.currval  from dual\", ");

            
            #line 38 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                                             
            
            #line default
            #line hidden
            
            #line 38 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                                        Write(Model.connectionVarName);

            
            #line default
            #line hidden
            
            #line 38 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                                                                                                                     
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

            
            #line 39 "..\..\SqlTemplate\oracle\Insert.cshtml"
					
            
            #line default
            #line hidden
            
            #line 39 "..\..\SqlTemplate\oracle\Insert.cshtml"
      if(Model.isTransaction){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("__");

            
            #line 40 "..\..\SqlTemplate\oracle\Insert.cshtml"
           
            
            #line default
            #line hidden
            
            #line 40 "..\..\SqlTemplate\oracle\Insert.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 40 "..\..\SqlTemplate\oracle\Insert.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 40 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 40 "..\..\SqlTemplate\oracle\Insert.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 40 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_command__.Transaction=");

            
            #line 40 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                          
            
            #line default
            #line hidden
            
            #line 40 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                     Write(Model.transactionVarName);

            
            #line default
            #line hidden
            
            #line 40 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                                                   
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

            
            #line 41 "..\..\SqlTemplate\oracle\Insert.cshtml"
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

            
            #line 42 "..\..\SqlTemplate\oracle\Insert.cshtml"
       
            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\oracle\Insert.cshtml"
  Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\oracle\Insert.cshtml"
                     
            
            #line default
            #line hidden
WriteLiteral(" = __");

            
            #line 42 "..\..\SqlTemplate\oracle\Insert.cshtml"
                             
            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\oracle\Insert.cshtml"
                        Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 42 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                    
            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                               Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                                                  
            
            #line default
            #line hidden
WriteLiteral("_command__.ExecuteScalar().AsVar();\r\n\t\t\t\t\t__");

            
            #line 43 "..\..\SqlTemplate\oracle\Insert.cshtml"
         
            
            #line default
            #line hidden
            
            #line 43 "..\..\SqlTemplate\oracle\Insert.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 43 "..\..\SqlTemplate\oracle\Insert.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 43 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 43 "..\..\SqlTemplate\oracle\Insert.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 43 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_command__.Dispose();\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\tcatch\r\n\t\t\t{\r\n\t\t\t\t__");

            
            #line 48 "..\..\SqlTemplate\oracle\Insert.cshtml"
        
            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\oracle\Insert.cshtml"
   Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\oracle\Insert.cshtml"
                           
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 48 "..\..\SqlTemplate\oracle\Insert.cshtml"
                               
            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\oracle\Insert.cshtml"
                          Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 48 "..\..\SqlTemplate\oracle\Insert.cshtml"
                                             
            
            #line default
            #line hidden
WriteLiteral("_command__.Dispose();\r\n\t\t\t}\r\n\t\t\t#endregion\r\n\t\t\t");

        }
    }
}
#pragma warning restore 1591
