#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFinal.Compile.SqlTemplate.oracle
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Struct : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\SqlTemplate\oracle\Struct.cshtml"
           
    public NFinal.Compile.SqlTemplate.Model.Struct Model { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("public struct __");

            
            #line 6 "..\..\SqlTemplate\oracle\Struct.cshtml"
                  
            
            #line default
            #line hidden
            
            #line 6 "..\..\SqlTemplate\oracle\Struct.cshtml"
             Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 6 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                     
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 6 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                         
            
            #line default
            #line hidden
            
            #line 6 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                    Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 6 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                       
            
            #line default
            #line hidden
WriteLiteral("__:NFinal.IModel\r\n\t\t{\r\n");

            
            #line 8 "..\..\SqlTemplate\oracle\Struct.cshtml"
			
            
            #line default
            #line hidden
            
            #line 8 "..\..\SqlTemplate\oracle\Struct.cshtml"
    foreach(var field in Model.fields){
			if(field.description!=null){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("/// <summary>\r\n");

WriteLiteral("            ");

WriteLiteral("/// ");

            
            #line 11 "..\..\SqlTemplate\oracle\Struct.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 11 "..\..\SqlTemplate\oracle\Struct.cshtml"
               Write(field.description);

            
            #line default
            #line hidden
            
            #line 11 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                      
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

WriteLiteral("/// </summary>\r\n");

            
            #line 13 "..\..\SqlTemplate\oracle\Struct.cshtml"
			}
			if(field.allowNull && field.isValueType){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("public ");

            
            #line 15 "..\..\SqlTemplate\oracle\Struct.cshtml"
              
            
            #line default
            #line hidden
            
            #line 15 "..\..\SqlTemplate\oracle\Struct.cshtml"
         Write(field.csharpType);

            
            #line default
            #line hidden
            
            #line 15 "..\..\SqlTemplate\oracle\Struct.cshtml"
                               
            
            #line default
            #line hidden
WriteLiteral("? ");

            
            #line 15 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 15 "..\..\SqlTemplate\oracle\Struct.cshtml"
                               Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 15 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                          
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

            
            #line 16 "..\..\SqlTemplate\oracle\Struct.cshtml"
			}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("public ");

            
            #line 17 "..\..\SqlTemplate\oracle\Struct.cshtml"
              
            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\oracle\Struct.cshtml"
         Write(field.csharpType);

            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\oracle\Struct.cshtml"
                               
            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 17 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                   
            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\oracle\Struct.cshtml"
                              Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 17 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                         
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

            
            #line 18 "..\..\SqlTemplate\oracle\Struct.cshtml"
			}
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 20 "..\..\SqlTemplate\oracle\Struct.cshtml"
    foreach(var structField in Model.structFields){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("public ");

            
            #line 21 "..\..\SqlTemplate\oracle\Struct.cshtml"
              
            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Struct.cshtml"
         Write(structField.typeName);

            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                   
            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 21 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                       
            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                  Write(structField.varName);

            
            #line default
            #line hidden
            
            #line 21 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                           
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

            
            #line 22 "..\..\SqlTemplate\oracle\Struct.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t#region Nullable\r\n\t\t\tprivate bool __is_null__;\r\n\t\t\tpublic bool __Is_Null__\r\n\t\t" +
"\t{\r\n\t\t\t\tget {\r\n\t\t\t\t\treturn __is_null__;\r\n\t\t\t\t}\r\n\t\t\t\tset\r\n\t\t\t\t{\r\n\t\t\t\t\t __is_null_" +
"_=value;\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\tpublic static implicit operator __");

            
            #line 35 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                       
            
            #line default
            #line hidden
            
            #line 35 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                  Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 35 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                          
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 35 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                              
            
            #line default
            #line hidden
            
            #line 35 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                         Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 35 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                                            
            
            #line default
            #line hidden
WriteLiteral("__(string __value__)\r\n\t\t\t{\r\n\t\t\t\tvar __value2__ = new __");

            
            #line 37 "..\..\SqlTemplate\oracle\Struct.cshtml"
                             
            
            #line default
            #line hidden
            
            #line 37 "..\..\SqlTemplate\oracle\Struct.cshtml"
                        Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 37 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 37 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                    
            
            #line default
            #line hidden
            
            #line 37 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                               Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 37 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                                  
            
            #line default
            #line hidden
WriteLiteral("__();\r\n\t\t\t\t__value2__.__Is_Null__ = __value__==null;\r\n\t\t\t\treturn __value2__;\r\n\t\t\t" +
"}\r\n\t\t\tpublic static  bool operator true(__");

            
            #line 41 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                         
            
            #line default
            #line hidden
            
            #line 41 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 41 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 41 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                                
            
            #line default
            #line hidden
            
            #line 41 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 41 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                                              
            
            #line default
            #line hidden
WriteLiteral("__ __value__)\r\n\t\t\t{\r\n\t\t\t\treturn !__value__.__is_null__;\r\n\t\t\t}\r\n\t\t\tpublic static b" +
"ool operator false(__");

            
            #line 45 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                         
            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 45 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                                
            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                                              
            
            #line default
            #line hidden
WriteLiteral("__ __value__)\r\n\t\t\t{\r\n\t\t\t\treturn !__value__.__is_null__;\r\n\t\t\t}\r\n\t\t\t#endregion\r\n\t\t\t" +
"#region 写Json字符串\r\n\t\t\tpublic void WriteJson(System.IO.TextWriter tw)\r\n\t\t\t{\r\n\t\t\t\tt" +
"w.Write(\"{\");\r\n");

            
            #line 54 "..\..\SqlTemplate\oracle\Struct.cshtml"
				
            
            #line default
            #line hidden
            
            #line 54 "..\..\SqlTemplate\oracle\Struct.cshtml"
      int i=0;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 55 "..\..\SqlTemplate\oracle\Struct.cshtml"
				
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\oracle\Struct.cshtml"
     foreach(var field in Model.fields){
					if(i!=0){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("tw.Write(\",\");\r\n");

            
            #line 58 "..\..\SqlTemplate\oracle\Struct.cshtml"
					}
					if(field.jsonType=="Number"){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"");

            
            #line 60 "..\..\SqlTemplate\oracle\Struct.cshtml"
                      
            
            #line default
            #line hidden
            
            #line 60 "..\..\SqlTemplate\oracle\Struct.cshtml"
                 Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 60 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral("\\\":\");\r\n");

            
            #line 61 "..\..\SqlTemplate\oracle\Struct.cshtml"
						if(field.allowNull){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("tw.Write(");

            
            #line 62 "..\..\SqlTemplate\oracle\Struct.cshtml"
                   
            
            #line default
            #line hidden
            
            #line 62 "..\..\SqlTemplate\oracle\Struct.cshtml"
              Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 62 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                         
            
            #line default
            #line hidden
WriteLiteral("==null?\"null\" : ");

            
            #line 62 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                            
            
            #line default
            #line hidden
            
            #line 62 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                       Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 62 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                                                  
            
            #line default
            #line hidden
WriteLiteral(".ToString());\r\n");

            
            #line 63 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("tw.Write(");

            
            #line 64 "..\..\SqlTemplate\oracle\Struct.cshtml"
                   
            
            #line default
            #line hidden
            
            #line 64 "..\..\SqlTemplate\oracle\Struct.cshtml"
              Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 64 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                         
            
            #line default
            #line hidden
WriteLiteral(".ToString());\r\n");

            
            #line 65 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}
					}else if(field.jsonType=="Bool"){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"");

            
            #line 67 "..\..\SqlTemplate\oracle\Struct.cshtml"
                      
            
            #line default
            #line hidden
            
            #line 67 "..\..\SqlTemplate\oracle\Struct.cshtml"
                 Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 67 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral("\\\":\");\r\n");

            
            #line 68 "..\..\SqlTemplate\oracle\Struct.cshtml"
						if(field.allowNull){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("tw.Write(");

            
            #line 69 "..\..\SqlTemplate\oracle\Struct.cshtml"
                   
            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\oracle\Struct.cshtml"
              Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                         
            
            #line default
            #line hidden
WriteLiteral("==null?\"null\":((bool)");

            
            #line 69 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                                 
            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                            Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 69 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                                                       
            
            #line default
            #line hidden
WriteLiteral("?\"true\":\"false\"));\r\n");

            
            #line 70 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("tw.Write(");

            
            #line 71 "..\..\SqlTemplate\oracle\Struct.cshtml"
                   
            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\oracle\Struct.cshtml"
              Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 71 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                         
            
            #line default
            #line hidden
WriteLiteral("?\"true\":\"false\");\r\n");

            
            #line 72 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}
					}else if(field.jsonType=="Time"){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"");

            
            #line 74 "..\..\SqlTemplate\oracle\Struct.cshtml"
                      
            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\oracle\Struct.cshtml"
                 Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 74 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral("\\\":\");\r\n");

            
            #line 75 "..\..\SqlTemplate\oracle\Struct.cshtml"
						if(field.allowNull){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("if(");

            
            #line 76 "..\..\SqlTemplate\oracle\Struct.cshtml"
             
            
            #line default
            #line hidden
            
            #line 76 "..\..\SqlTemplate\oracle\Struct.cshtml"
        Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 76 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                   
            
            #line default
            #line hidden
WriteLiteral("==null)\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("{\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"null\");\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("}\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("else\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("{\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(");

            
            #line 83 "..\..\SqlTemplate\oracle\Struct.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 83 "..\..\SqlTemplate\oracle\Struct.cshtml"
               Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 83 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                          
            
            #line default
            #line hidden
WriteLiteral(".ToString());\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("}\r\n");

            
            #line 86 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(");

            
            #line 88 "..\..\SqlTemplate\oracle\Struct.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 88 "..\..\SqlTemplate\oracle\Struct.cshtml"
               Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 88 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                          
            
            #line default
            #line hidden
WriteLiteral(".ToString());\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

            
            #line 90 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}
					}else if(field.jsonType=="String"){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"");

            
            #line 92 "..\..\SqlTemplate\oracle\Struct.cshtml"
                      
            
            #line default
            #line hidden
            
            #line 92 "..\..\SqlTemplate\oracle\Struct.cshtml"
                 Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 92 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral("\\\":\");\r\n");

            
            #line 93 "..\..\SqlTemplate\oracle\Struct.cshtml"
						if(field.allowNull){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("if(");

            
            #line 94 "..\..\SqlTemplate\oracle\Struct.cshtml"
             
            
            #line default
            #line hidden
            
            #line 94 "..\..\SqlTemplate\oracle\Struct.cshtml"
        Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 94 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                   
            
            #line default
            #line hidden
WriteLiteral("==null)\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("{\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"null\");\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("}\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("else\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("{\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(");

            
            #line 101 "..\..\SqlTemplate\oracle\Struct.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 101 "..\..\SqlTemplate\oracle\Struct.cshtml"
               Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 101 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                          
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("}\r\n");

            
            #line 104 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(");

            
            #line 106 "..\..\SqlTemplate\oracle\Struct.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 106 "..\..\SqlTemplate\oracle\Struct.cshtml"
               Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 106 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                          
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

            
            #line 108 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}
					}else if(field.jsonType=="Object"){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"");

            
            #line 110 "..\..\SqlTemplate\oracle\Struct.cshtml"
                      
            
            #line default
            #line hidden
            
            #line 110 "..\..\SqlTemplate\oracle\Struct.cshtml"
                 Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 110 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral("\\\":\");\r\n");

            
            #line 111 "..\..\SqlTemplate\oracle\Struct.cshtml"
						if(field.allowNull){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("if(");

            
            #line 112 "..\..\SqlTemplate\oracle\Struct.cshtml"
             
            
            #line default
            #line hidden
            
            #line 112 "..\..\SqlTemplate\oracle\Struct.cshtml"
        Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 112 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                   
            
            #line default
            #line hidden
WriteLiteral("==null)\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("{\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"null\");\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("}\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("else\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("{\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(");

            
            #line 119 "..\..\SqlTemplate\oracle\Struct.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 119 "..\..\SqlTemplate\oracle\Struct.cshtml"
               Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 119 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                          
            
            #line default
            #line hidden
WriteLiteral(".ToString());\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("}\r\n");

            
            #line 122 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(");

            
            #line 124 "..\..\SqlTemplate\oracle\Struct.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 124 "..\..\SqlTemplate\oracle\Struct.cshtml"
               Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 124 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                          
            
            #line default
            #line hidden
WriteLiteral(".ToString());\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

            
            #line 126 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}
					}else if(field.jsonType=="Base64"){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"");

            
            #line 128 "..\..\SqlTemplate\oracle\Struct.cshtml"
                      
            
            #line default
            #line hidden
            
            #line 128 "..\..\SqlTemplate\oracle\Struct.cshtml"
                 Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 128 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral("\\\":\");\r\n");

            
            #line 129 "..\..\SqlTemplate\oracle\Struct.cshtml"
						if(field.allowNull){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("if(");

            
            #line 130 "..\..\SqlTemplate\oracle\Struct.cshtml"
             
            
            #line default
            #line hidden
            
            #line 130 "..\..\SqlTemplate\oracle\Struct.cshtml"
        Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 130 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                   
            
            #line default
            #line hidden
WriteLiteral("==null)\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("{\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"null\");\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("}\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("else\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("{\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(Convert.ToBase64String(");

            
            #line 137 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                           
            
            #line default
            #line hidden
            
            #line 137 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                      Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 137 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                                 
            
            #line default
            #line hidden
WriteLiteral("));\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t");

WriteLiteral("}\r\n");

            
            #line 140 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(Convert.ToBase64String(");

            
            #line 142 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                           
            
            #line default
            #line hidden
            
            #line 142 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                      Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 142 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                                                 
            
            #line default
            #line hidden
WriteLiteral("));\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

            
            #line 144 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}
					}
				i++;
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t");

            
            #line 148 "..\..\SqlTemplate\oracle\Struct.cshtml"
     foreach(var structField in Model.structFields){
					if(structField.isSimple){
						if(structField.isNumber){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\",\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"");

            
            #line 152 "..\..\SqlTemplate\oracle\Struct.cshtml"
                       
            
            #line default
            #line hidden
            
            #line 152 "..\..\SqlTemplate\oracle\Struct.cshtml"
                  Write(structField.varName);

            
            #line default
            #line hidden
            
            #line 152 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                           
            
            #line default
            #line hidden
WriteLiteral("\\\":\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(");

            
            #line 153 "..\..\SqlTemplate\oracle\Struct.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 153 "..\..\SqlTemplate\oracle\Struct.cshtml"
               Write(structField.varName);

            
            #line default
            #line hidden
            
            #line 153 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                        
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

            
            #line 154 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}else if(structField.isBoolean){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\",\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"");

            
            #line 156 "..\..\SqlTemplate\oracle\Struct.cshtml"
                       
            
            #line default
            #line hidden
            
            #line 156 "..\..\SqlTemplate\oracle\Struct.cshtml"
                  Write(structField.varName);

            
            #line default
            #line hidden
            
            #line 156 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                           
            
            #line default
            #line hidden
WriteLiteral("\\\":\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(");

            
            #line 157 "..\..\SqlTemplate\oracle\Struct.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 157 "..\..\SqlTemplate\oracle\Struct.cshtml"
               Write(structField.varName);

            
            #line default
            #line hidden
            
            #line 157 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                        
            
            #line default
            #line hidden
WriteLiteral("?\"true\":\"false\");\r\n");

            
            #line 158 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\",\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"");

            
            #line 160 "..\..\SqlTemplate\oracle\Struct.cshtml"
                       
            
            #line default
            #line hidden
            
            #line 160 "..\..\SqlTemplate\oracle\Struct.cshtml"
                  Write(structField.varName);

            
            #line default
            #line hidden
            
            #line 160 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                           
            
            #line default
            #line hidden
WriteLiteral("\\\":\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("if(");

            
            #line 161 "..\..\SqlTemplate\oracle\Struct.cshtml"
              
            
            #line default
            #line hidden
            
            #line 161 "..\..\SqlTemplate\oracle\Struct.cshtml"
         Write(structField.varName);

            
            #line default
            #line hidden
            
            #line 161 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                  
            
            #line default
            #line hidden
WriteLiteral("==null)\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("{\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"null\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("}\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("else\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("{\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t");

WriteLiteral("WriteString(");

            
            #line 168 "..\..\SqlTemplate\oracle\Struct.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 168 "..\..\SqlTemplate\oracle\Struct.cshtml"
                   Write(structField.varName);

            
            #line default
            #line hidden
            
            #line 168 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral(".ToString(),tw);\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"\");\r\n");

WriteLiteral("\t\t\t\t\t\t    ");

WriteLiteral("}\r\n");

            
            #line 171 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}
					}else{
						if(structField.isList){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\",\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"");

            
            #line 175 "..\..\SqlTemplate\oracle\Struct.cshtml"
                       
            
            #line default
            #line hidden
            
            #line 175 "..\..\SqlTemplate\oracle\Struct.cshtml"
                  Write(structField.varName);

            
            #line default
            #line hidden
            
            #line 175 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                           
            
            #line default
            #line hidden
WriteLiteral("\\\":\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 176 "..\..\SqlTemplate\oracle\Struct.cshtml"
           
            
            #line default
            #line hidden
            
            #line 176 "..\..\SqlTemplate\oracle\Struct.cshtml"
      Write(structField.varName);

            
            #line default
            #line hidden
            
            #line 176 "..\..\SqlTemplate\oracle\Struct.cshtml"
                               
            
            #line default
            #line hidden
WriteLiteral(".WriteJson(tw);\r\n");

            
            #line 177 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\",\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

WriteLiteral("tw.Write(\"\\\"");

            
            #line 179 "..\..\SqlTemplate\oracle\Struct.cshtml"
                       
            
            #line default
            #line hidden
            
            #line 179 "..\..\SqlTemplate\oracle\Struct.cshtml"
                  Write(structField.varName);

            
            #line default
            #line hidden
            
            #line 179 "..\..\SqlTemplate\oracle\Struct.cshtml"
                                           
            
            #line default
            #line hidden
WriteLiteral("\\\":\");\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 180 "..\..\SqlTemplate\oracle\Struct.cshtml"
           
            
            #line default
            #line hidden
            
            #line 180 "..\..\SqlTemplate\oracle\Struct.cshtml"
      Write(structField.varName);

            
            #line default
            #line hidden
            
            #line 180 "..\..\SqlTemplate\oracle\Struct.cshtml"
                               
            
            #line default
            #line hidden
WriteLiteral(".WriteJson(tw);\r\n");

            
            #line 181 "..\..\SqlTemplate\oracle\Struct.cshtml"
						}
					}
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\ttw.Write(\"}\");\r\n\t\t\t}\r\n\t\t\t#endregion\r\n\t\t}\r\n\t\t");

        }
    }
}
#pragma warning restore 1591
