#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFinal.Compile.Template.Startup
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Url : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\Template\Startup\Url.cshtml"
           
    public Compile.Template.Startup.UrlModel Model { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("namespace ");

            
            #line 6 "..\..\Template\Startup\Url.cshtml"
            
            
            #line default
            #line hidden
            
            #line 6 "..\..\Template\Startup\Url.cshtml"
       Write(Model.project);

            
            #line default
            #line hidden
            
            #line 6 "..\..\Template\Startup\Url.cshtml"
                          
            
            #line default
            #line hidden
WriteLiteral("\r\n{\r\n    public class Url\r\n    {\r\n\t\tprivate static string __ParseUrl__(string __u" +
"rl__)\r\n        {\r\n            switch (__url__)\r\n            {\r\n");

            
            #line 14 "..\..\Template\Startup\Url.cshtml"
				
            
            #line default
            #line hidden
            
            #line 14 "..\..\Template\Startup\Url.cshtml"
     foreach(var rewriteFile in Model.rewriteData.rewriteFileList){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t");

WriteLiteral("case \"");

            
            #line 15 "..\..\Template\Startup\Url.cshtml"
              
            
            #line default
            #line hidden
            
            #line 15 "..\..\Template\Startup\Url.cshtml"
         Write(rewriteFile.to);

            
            #line default
            #line hidden
            
            #line 15 "..\..\Template\Startup\Url.cshtml"
                             
            
            #line default
            #line hidden
WriteLiteral("\":__url__ = \"");

            
            #line 15 "..\..\Template\Startup\Url.cshtml"
                                             
            
            #line default
            #line hidden
            
            #line 15 "..\..\Template\Startup\Url.cshtml"
                                        Write(rewriteFile.from);

            
            #line default
            #line hidden
            
            #line 15 "..\..\Template\Startup\Url.cshtml"
                                                              
            
            #line default
            #line hidden
WriteLiteral("\"; break;\r\n");

            
            #line 16 "..\..\Template\Startup\Url.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\tdefault: break;\r\n            }\r\n");

            
            #line 19 "..\..\Template\Startup\Url.cshtml"
			
            
            #line default
            #line hidden
            
            #line 19 "..\..\Template\Startup\Url.cshtml"
    foreach(var rewriteDirectory in Model.rewriteData.rewriteDirectoryList){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("if(__url__.StartsWith(\"");

            
            #line 20 "..\..\Template\Startup\Url.cshtml"
                              
            
            #line default
            #line hidden
            
            #line 20 "..\..\Template\Startup\Url.cshtml"
                         Write(rewriteDirectory.to);

            
            #line default
            #line hidden
            
            #line 20 "..\..\Template\Startup\Url.cshtml"
                                                  
            
            #line default
            #line hidden
WriteLiteral("\"))\r\n");

WriteLiteral("\t\t\t");

WriteLiteral("{\r\n");

WriteLiteral("\t\t\t\t");

WriteLiteral("__url__ = \"");

            
            #line 22 "..\..\Template\Startup\Url.cshtml"
                   
            
            #line default
            #line hidden
            
            #line 22 "..\..\Template\Startup\Url.cshtml"
              Write(rewriteDirectory.from);

            
            #line default
            #line hidden
            
            #line 22 "..\..\Template\Startup\Url.cshtml"
                                         
            
            #line default
            #line hidden
WriteLiteral("\" + __url__.Remove(0,\"");

            
            #line 22 "..\..\Template\Startup\Url.cshtml"
                                                                  
            
            #line default
            #line hidden
            
            #line 22 "..\..\Template\Startup\Url.cshtml"
                                                             Write(rewriteDirectory.to);

            
            #line default
            #line hidden
            
            #line 22 "..\..\Template\Startup\Url.cshtml"
                                                                                      
            
            #line default
            #line hidden
WriteLiteral("\".Length);\r\n");

WriteLiteral("\t\t\t");

WriteLiteral("}\r\n");

            
            #line 24 "..\..\Template\Startup\Url.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("            return __url__;\r\n        }\r\n");

            
            #line 27 "..\..\Template\Startup\Url.cshtml"
        
            
            #line default
            #line hidden
            
            #line 27 "..\..\Template\Startup\Url.cshtml"
          int i=1;
		foreach(var fileData in Model.controllerFileDataList){
		foreach(var classData in fileData.ClassDataList){
		foreach(var methodData in classData.MethodDataList){
        if(methodData.isPublic){

            
            #line default
            #line hidden
WriteLiteral("\t\t");

            
            #line 32 "..\..\Template\Startup\Url.cshtml"
Write(methodData.CommitString);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t");

WriteLiteral("public static string ");

            
            #line 33 "..\..\Template\Startup\Url.cshtml"
                           
            
            #line default
            #line hidden
            
            #line 33 "..\..\Template\Startup\Url.cshtml"
                      Write(fileData.appName);

            
            #line default
            #line hidden
            
            #line 33 "..\..\Template\Startup\Url.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 33 "..\..\Template\Startup\Url.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 33 "..\..\Template\Startup\Url.cshtml"
                                           Write(classData.name);

            
            #line default
            #line hidden
            
            #line 33 "..\..\Template\Startup\Url.cshtml"
                                                               
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 33 "..\..\Template\Startup\Url.cshtml"
                                                                   
            
            #line default
            #line hidden
            
            #line 33 "..\..\Template\Startup\Url.cshtml"
                                                              Write(methodData.name);

            
            #line default
            #line hidden
            
            #line 33 "..\..\Template\Startup\Url.cshtml"
                                                                                   
            
            #line default
            #line hidden
WriteLiteral("(");

            
            #line 33 "..\..\Template\Startup\Url.cshtml"
                                                                                       
            
            #line default
            #line hidden
            
            #line 33 "..\..\Template\Startup\Url.cshtml"
                                                                                  Write(methodData.urlParser.formatParameterTypeAndNames);

            
            #line default
            #line hidden
            
            #line 33 "..\..\Template\Startup\Url.cshtml"
                                                                                                                                        
            
            #line default
            #line hidden
WriteLiteral(")\r\n");

WriteLiteral("        ");

WriteLiteral("{\r\n");

WriteLiteral("            ");

WriteLiteral("string __url__=string.Format(\"");

            
            #line 35 "..\..\Template\Startup\Url.cshtml"
                                              
            
            #line default
            #line hidden
            
            #line 35 "..\..\Template\Startup\Url.cshtml"
                                         Write(methodData.urlParser.formatUrl);

            
            #line default
            #line hidden
            
            #line 35 "..\..\Template\Startup\Url.cshtml"
                                                                             
            
            #line default
            #line hidden
WriteLiteral("\"");

            
            #line 35 "..\..\Template\Startup\Url.cshtml"
                                                                                 
            
            #line default
            #line hidden
            
            #line 35 "..\..\Template\Startup\Url.cshtml"
                                                                            Write(methodData.urlParser.formatParameters);

            
            #line default
            #line hidden
            
            #line 35 "..\..\Template\Startup\Url.cshtml"
                                                                                                                       
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

WriteLiteral("\t\t\t");

WriteLiteral("__url__ = __ParseUrl__(__url__);\r\n");

WriteLiteral("            ");

WriteLiteral("return __url__;\r\n");

WriteLiteral("        ");

WriteLiteral("}\r\n");

            
            #line 39 "..\..\Template\Startup\Url.cshtml"
		i++;
		}
		}
		}
		}
		
            
            #line default
            #line hidden
WriteLiteral("\r\n    }\r\n}\r\n");

        }
    }
}
#pragma warning restore 1591
