// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace NFinal.Config
{

    public class ConnectionString
    {

        /// <summary>
        /// Examples: "Common"
        /// </summary>
        public string name;

        /// <summary>
        /// Examples: "Data Source=|ModuleDataDirectory|Common.db;Pooling=true;FailIfMissing=false"
        /// </summary>
        public string connectionString;

        /// <summary>
        /// Examples: "System.Data.SQLite"
        /// </summary>
        public string providerName;
    }

    public class RewriteDirectory
    {

        /// <summary>
        /// Examples: ""
        /// </summary>
        public string from;

        /// <summary>
        /// Examples: ""
        /// </summary>
        public string to;
    }

    public class RewriteFile
    {

        /// <summary>
        /// Examples: ""
        /// </summary>
        public string from;

        /// <summary>
        /// Examples: ""
        /// </summary>
        public string to;
    }

    public class Redis
    {

        /// <summary>
        /// Examples: true
        /// </summary>
        public bool autoStart;

        /// <summary>
        /// Examples: 60
        /// </summary>
        public int maxReadPoolSize;

        /// <summary>
        /// Examples: 60
        /// </summary>
        public int maxWritePoolSize;

        /// <summary>
        /// Examples: ["127.0.0.1:6379"]
        /// </summary>
        public IList<string> readWriteHosts;

        /// <summary>
        /// Examples: ["127.0.0.1:6379"]
        /// </summary>
        public IList<string> readOnlyHosts;
    }

}

namespace NFinal.Config
{

    public class config
    {

        /// <summary>
        /// Examples: "/DDD"
        /// </summary>
        public string urlPrefix;

        /// <summary>
        /// Examples: "DDD_"
        /// </summary>
        public string cookiePrefix;

        /// <summary>
        /// Examples: "DDD_"
        /// </summary>
        public string sessionPrefix;

        /// <summary>
        /// Examples: "Default"
        /// </summary>
        public string defaultStyle;

        /// <summary>
        /// Examples: ".html"
        /// </summary>
        public string urlExtension;

        /// <summary>
        /// Examples: "1"
        /// </summary>
        public string urlMode;

        /// <summary>
        /// Examples: "1.0"
        /// </summary>
        public string version;

        /// <summary>
        /// Examples: false
        /// </summary>
        public bool autoVersion;

        /// <summary>
        /// Examples: true
        /// </summary>
        public bool compressHTML;

        /// <summary>
        /// Examples: [{"name":"Common","connectionString":"Data Source=|ModuleDataDirectory|Common.db;Pooling=true;FailIfMissing=false","providerName":"System.Data.SQLite"}]
        /// </summary>
        public IList<ConnectionString> connectionStrings;

        /// <summary>
        /// Examples: [{"from":"","to":""}]
        /// </summary>
        public IList<RewriteDirectory> rewriteDirectory;

        /// <summary>
        /// Examples: [{"from":"","to":""}]
        /// </summary>
        public IList<RewriteFile> rewriteFile;

        /// <summary>
        /// Examples: {"autoStart":true,"maxReadPoolSize":60,"maxWritePoolSize":60,"readWriteHosts":["127.0.0.1:6379"],"readOnlyHosts":["127.0.0.1:6379"]}
        /// </summary>
        public Redis redis;
    }

}
