// Generated by Lucas
// http://help.nfinal.com

using System;
using System.Collections.Generic;

namespace Code
{

    public class my
    {

        /// <summary>
        /// Examples: 1
        /// </summary>
        public int a;

        /// <summary>
        /// Examples: true
        /// </summary>
        public bool b;
    }

}
