#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFinal.Compile.Template
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Debug : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\Template\Debug.cshtml"
           
    public NFinal.Compile.Template.DebugModel Model { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("﻿\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n<head>\r\n<meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral("/>\r\n    <title></title>\r\n    <meta");

WriteLiteral(" http-equiv=\"Cache-Control\"");

WriteLiteral(" content=\"no-cache\"");

WriteLiteral(">\r\n    <script");

WriteLiteral(" src=\"/Scripts/jquery-1.11.2.min.js\"");

WriteLiteral("></script>\r\n</head>\r\n<body>\r\n    <script>\r\n        $.getScript(\"/Scripts/Url.js?_" +
"\" + Math.random(), function () {\r\n");

            
            #line 17 "..\..\Template\Debug.cshtml"
            
            
            #line default
            #line hidden
            
            #line 17 "..\..\Template\Debug.cshtml"
             foreach(var parameter in Model.parameterDataList){
			if(parameter.isUrlParameter){
			if(parameter.type=="int"){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("var ");

            
            #line 20 "..\..\Template\Debug.cshtml"
           
            
            #line default
            #line hidden
            
            #line 20 "..\..\Template\Debug.cshtml"
      Write(parameter.name);

            
            #line default
            #line hidden
            
            #line 20 "..\..\Template\Debug.cshtml"
                          
            
            #line default
            #line hidden
WriteLiteral("=1;\r\n");

            
            #line 21 "..\..\Template\Debug.cshtml"
			}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("var ");

            
            #line 22 "..\..\Template\Debug.cshtml"
           
            
            #line default
            #line hidden
            
            #line 22 "..\..\Template\Debug.cshtml"
      Write(parameter.name);

            
            #line default
            #line hidden
            
            #line 22 "..\..\Template\Debug.cshtml"
                          
            
            #line default
            #line hidden
WriteLiteral("=\"\";\r\n");

            
            #line 23 "..\..\Template\Debug.cshtml"
			}
			}
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\twindow.location.href = Url.");

            
            #line 26 "..\..\Template\Debug.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 26 "..\..\Template\Debug.cshtml"
                           Write(Model.methodName);

            
            #line default
            #line hidden
            
            #line 26 "..\..\Template\Debug.cshtml"
                                                 
            
            #line default
            #line hidden
WriteLiteral("(");

            
            #line 26 "..\..\Template\Debug.cshtml"
                                                     
            
            #line default
            #line hidden
            
            #line 26 "..\..\Template\Debug.cshtml"
                                                Write(Model.methodParameters);

            
            #line default
            #line hidden
            
            #line 26 "..\..\Template\Debug.cshtml"
                                                                            
            
            #line default
            #line hidden
WriteLiteral(");\r\n        });\r\n\t</script>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
