#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFinal.Compile.SqlTemplate.mysql
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class QueryAll : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 3 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
           
    public NFinal.Compile.SqlTemplate.Model.QueryAll Model { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\t#region\tvar ");

            
            #line 6 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
               
            
            #line default
            #line hidden
            
            #line 6 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
          Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 6 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                             
            
            #line default
            #line hidden
WriteLiteral(";选取所有记录\r\n");

            
            #line 7 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
			
            
            #line default
            #line hidden
            
            #line 7 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
    if(Model.hasGenericType){
			if(Model.isDeclaration){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("List<");

            
            #line 9 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
            
            
            #line default
            #line hidden
            
            #line 9 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
       Write(Model.type);

            
            #line default
            #line hidden
            
            #line 9 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                       
            
            #line default
            #line hidden
WriteLiteral("> ");

            
            #line 9 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 9 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                       Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 9 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                          
            
            #line default
            #line hidden
WriteLiteral("=new List<");

            
            #line 9 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                       
            
            #line default
            #line hidden
            
            #line 9 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                  Write(Model.type);

            
            #line default
            #line hidden
            
            #line 9 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                  
            
            #line default
            #line hidden
WriteLiteral(">();\r\n");

            
            #line 10 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
			}
			}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("var ");

            
            #line 12 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
           
            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                         
            
            #line default
            #line hidden
WriteLiteral(" = new List<__");

            
            #line 12 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                          
            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                     Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                             
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 12 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                 
            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                            Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 12 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                               
            
            #line default
            #line hidden
WriteLiteral("__>();\r\n");

            
            #line 13 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\t\t\tvar __");

            
            #line 14 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
           
            
            #line default
            #line hidden
            
            #line 14 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 14 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 14 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 14 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 14 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_command__ = new MySql.Data.MySqlClient.MySqlCommand(\"");

            
            #line 14 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                         
            
            #line default
            #line hidden
            
            #line 14 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                    Write(Model.sql);

            
            #line default
            #line hidden
            
            #line 14 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                   
            
            #line default
            #line hidden
WriteLiteral("\",");

            
            #line 14 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                        
            
            #line default
            #line hidden
            
            #line 14 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                   Write(Model.connectionVarName);

            
            #line default
            #line hidden
            
            #line 14 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

            
            #line 15 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
			
            
            #line default
            #line hidden
            
            #line 15 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
    if(Model.isTransaction){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 16 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
         
            
            #line default
            #line hidden
            
            #line 16 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 16 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 16 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 16 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 16 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_command__.Transaction=");

            
            #line 16 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                        
            
            #line default
            #line hidden
            
            #line 16 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                   Write(Model.transactionVarName);

            
            #line default
            #line hidden
            
            #line 16 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                 
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

            
            #line 17 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 18 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
    if(Model.sqlVarParameters.Count>0){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("var __");

            
            #line 19 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
             
            
            #line default
            #line hidden
            
            #line 19 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
        Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 19 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 19 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 19 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                               Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 19 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                  
            
            #line default
            #line hidden
WriteLiteral("_parameters__=new MySql.Data.MySqlClient.MySqlParameter[");

            
            #line 19 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                             
            
            #line default
            #line hidden
            
            #line 19 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                        Write(Model.sqlVarParameters.Count);

            
            #line default
            #line hidden
            
            #line 19 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                          
            
            #line default
            #line hidden
WriteLiteral("];\r\n");

            
            #line 20 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 21 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
     int i=0;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 22 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
			
            
            #line default
            #line hidden
            
            #line 22 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
    foreach(var sqlVarParameter in Model.sqlVarParameters){
				if(sqlVarParameter.field!=null){
					if(sqlVarParameter.field.length>0){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("__");

            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
           
            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                          Write(i);

            
            #line default
            #line hidden
WriteLiteral("] = new MySql.Data.MySqlClient.MySqlParameter(\"?");

            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                   
            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                              Write(sqlVarParameter.name);

            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                        
            
            #line default
            #line hidden
WriteLiteral("\",MySql.Data.MySqlClient.MySqlDbType.");

            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                
            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                           Write(sqlVarParameter.field.dbType);

            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                             
            
            #line default
            #line hidden
WriteLiteral(",");

            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                 
            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                            Write(sqlVarParameter.field.length);

            
            #line default
            #line hidden
            
            #line 25 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                              
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

WriteLiteral("\t\t\t\t\t");

WriteLiteral("__");

            
            #line 26 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
           
            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 26 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 26 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                          Write(i);

            
            #line default
            #line hidden
WriteLiteral("].Value = ");

            
            #line 26 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                             
            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                        Write(sqlVarParameter.csharpName);

            
            #line default
            #line hidden
            
            #line 26 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                        
            
            #line default
            #line hidden
WriteLiteral(".WithDBNull();\r\n");

            
            #line 27 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
					}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("__");

            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
           
            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                          Write(i);

            
            #line default
            #line hidden
WriteLiteral("] = new MySql.Data.MySqlClient.MySqlParameter(\"?");

            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                   
            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                              Write(sqlVarParameter.name);

            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                        
            
            #line default
            #line hidden
WriteLiteral("\",MySql.Data.MySqlClient.MySqlDbType.");

            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                
            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                           Write(sqlVarParameter.field.dbType);

            
            #line default
            #line hidden
            
            #line 28 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                             
            
            #line default
            #line hidden
WriteLiteral(");\r\n");

WriteLiteral("\t\t\t\t\t");

WriteLiteral("__");

            
            #line 29 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
           
            
            #line default
            #line hidden
            
            #line 29 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 29 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 29 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 29 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 29 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 29 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                          Write(i);

            
            #line default
            #line hidden
WriteLiteral("].Value = ");

            
            #line 29 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                             
            
            #line default
            #line hidden
            
            #line 29 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                        Write(sqlVarParameter.csharpName);

            
            #line default
            #line hidden
            
            #line 29 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                        
            
            #line default
            #line hidden
WriteLiteral(".WithDBNull();\r\n");

            
            #line 30 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
					}
				}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("__");

            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
           
            
            #line default
            #line hidden
            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_parameters__[");

            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                          Write(i);

            
            #line default
            #line hidden
WriteLiteral("] = new MySql.Data.MySqlClient.MySqlParameter(\"?");

            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                   
            
            #line default
            #line hidden
            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                              Write(sqlVarParameter.name);

            
            #line default
            #line hidden
            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                        
            
            #line default
            #line hidden
WriteLiteral("\",");

            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                             
            
            #line default
            #line hidden
            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                        Write(sqlVarParameter.name);

            
            #line default
            #line hidden
            
            #line 32 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                  
            
            #line default
            #line hidden
WriteLiteral(".WithDBNull());\r\n");

            
            #line 33 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
				}
				i++;
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 36 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
    if(Model.sqlVarParameters.Count>0){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

WriteLiteral("__");

            
            #line 37 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
         
            
            #line default
            #line hidden
            
            #line 37 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 37 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 37 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 37 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 37 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                              
            
            #line default
            #line hidden
WriteLiteral("_command__.Parameters.AddRange(__");

            
            #line 37 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                  
            
            #line default
            #line hidden
            
            #line 37 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                             Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 37 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                     
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 37 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                         
            
            #line default
            #line hidden
            
            #line 37 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                    Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 37 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                       
            
            #line default
            #line hidden
WriteLiteral("_parameters__);\r\n");

            
            #line 38 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t\tvar __");

            
            #line 39 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
           
            
            #line default
            #line hidden
            
            #line 39 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 39 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 39 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 39 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 39 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_reader__= __");

            
            #line 39 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                
            
            #line default
            #line hidden
            
            #line 39 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                           Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 39 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                   
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 39 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                       
            
            #line default
            #line hidden
            
            #line 39 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                  Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 39 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                     
            
            #line default
            #line hidden
WriteLiteral("_command__.ExecuteReader();\r\n\t\t\tif (__");

            
            #line 40 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
           
            
            #line default
            #line hidden
            
            #line 40 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 40 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 40 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 40 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 40 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_reader__.HasRows)\r\n\t\t\t{\r\n\t\t\t\twhile (__");

            
            #line 42 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
               
            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
          Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 42 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                      
            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                 Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 42 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                    
            
            #line default
            #line hidden
WriteLiteral("_reader__.Read())\r\n\t\t\t\t{\r\n");

            
            #line 44 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
					
            
            #line default
            #line hidden
            
            #line 44 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      if(Model.hasGenericType){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("var __");

            
            #line 45 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
               
            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
          Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 45 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                      
            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                 Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                    
            
            #line default
            #line hidden
WriteLiteral("_temp__ = new ");

            
            #line 45 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                     
            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                Write(Model.type);

            
            #line default
            #line hidden
            
            #line 45 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                
            
            #line default
            #line hidden
WriteLiteral("();\r\n");

            
            #line 46 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
					}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("var __");

            
            #line 47 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
               
            
            #line default
            #line hidden
            
            #line 47 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
          Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 47 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 47 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                      
            
            #line default
            #line hidden
            
            #line 47 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                 Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 47 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                    
            
            #line default
            #line hidden
WriteLiteral("_temp__ = new __");

            
            #line 47 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                       
            
            #line default
            #line hidden
            
            #line 47 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                  Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 47 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                          
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 47 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                              
            
            #line default
            #line hidden
            
            #line 47 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                         Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 47 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                            
            
            #line default
            #line hidden
WriteLiteral("__();\r\n");

            
            #line 48 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

            
            #line 49 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
       i=0;
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 50 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
					
            
            #line default
            #line hidden
            
            #line 50 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      foreach(var field in Model.fields){
					if(field.allowNull){
					if(field.isValueType){

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("if(!__");

            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
               
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
          Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                      
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                 Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                    
            
            #line default
            #line hidden
WriteLiteral("_reader__.IsDBNull(");

            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                   Write(i);

            
            #line default
            #line hidden
WriteLiteral(")){__");

            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                 
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                            Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                    
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                        
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                   Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                      
            
            #line default
            #line hidden
WriteLiteral("_temp__.");

            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                 
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                            Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                       
            
            #line default
            #line hidden
WriteLiteral(" =");

            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                            
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                       Write(field.GetMethodConvert);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                   
            
            #line default
            #line hidden
WriteLiteral(" __");

            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                         
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                              
            
            #line default
            #line hidden
WriteLiteral("_reader__.");

            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                           
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                      Write(field.GetMethodName);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                                               
            
            #line default
            #line hidden
WriteLiteral("(");

            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                                            Write(i);

            
            #line default
            #line hidden
WriteLiteral(")");

            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                                                      
            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                                                 Write(field.GetMethodValue);

            
            #line default
            #line hidden
            
            #line 53 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                                                                           
            
            #line default
            #line hidden
WriteLiteral(";}\r\n");

            
            #line 54 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
					}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("__");

            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
           
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_temp__.");

            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                           
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                      Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                 
            
            #line default
            #line hidden
WriteLiteral(" =__");

            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                        
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                   Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                           
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                               
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                          Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                             
            
            #line default
            #line hidden
WriteLiteral("_reader__.IsDBNull(");

            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                            Write(i);

            
            #line default
            #line hidden
WriteLiteral(")?null:");

            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                            
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                       Write(field.GetMethodConvert);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                   
            
            #line default
            #line hidden
WriteLiteral(" __");

            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                         
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                    Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                            
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                           Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                              
            
            #line default
            #line hidden
WriteLiteral("_reader__.");

            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                           
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                      Write(field.GetMethodName);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                                               
            
            #line default
            #line hidden
WriteLiteral("(");

            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                                            Write(i);

            
            #line default
            #line hidden
WriteLiteral(")");

            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                                                      
            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                                                 Write(field.GetMethodValue);

            
            #line default
            #line hidden
            
            #line 55 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                                                                                           
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

            
            #line 56 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
					}
					}else{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

WriteLiteral("__");

            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
           
            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
      Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                              
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                  
            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                             Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                
            
            #line default
            #line hidden
WriteLiteral("_temp__.");

            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                           
            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                      Write(field.structFieldName);

            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                 
            
            #line default
            #line hidden
WriteLiteral(" =");

            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                      
            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                 Write(field.GetMethodConvert);

            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                             
            
            #line default
            #line hidden
WriteLiteral(" __");

            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                   
            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                              Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                      
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                          
            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                     Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                        
            
            #line default
            #line hidden
WriteLiteral("_reader__.");

            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                     
            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                Write(field.GetMethodName);

            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                         
            
            #line default
            #line hidden
WriteLiteral("(");

            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                      Write(i);

            
            #line default
            #line hidden
WriteLiteral(")");

            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                
            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                           Write(field.GetMethodValue);

            
            #line default
            #line hidden
            
            #line 58 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                                                                                                                                                                     
            
            #line default
            #line hidden
WriteLiteral(";\r\n");

            
            #line 59 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
					}
					i++;
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t");

            
            #line 62 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
       
            
            #line default
            #line hidden
            
            #line 62 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
  Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 62 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                     
            
            #line default
            #line hidden
WriteLiteral(".Add(__");

            
            #line 62 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                               
            
            #line default
            #line hidden
            
            #line 62 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                          Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 62 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                  
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 62 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                      
            
            #line default
            #line hidden
            
            #line 62 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                 Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 62 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                                                    
            
            #line default
            #line hidden
WriteLiteral("_temp__);\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\t__");

            
            #line 65 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
       
            
            #line default
            #line hidden
            
            #line 65 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
  Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 65 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                          
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 65 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                              
            
            #line default
            #line hidden
            
            #line 65 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                         Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 65 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral("_reader__.Dispose();\r\n\t\t\t__");

            
            #line 66 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
       
            
            #line default
            #line hidden
            
            #line 66 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
  Write(Model.functionName);

            
            #line default
            #line hidden
            
            #line 66 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                          
            
            #line default
            #line hidden
WriteLiteral("_");

            
            #line 66 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                              
            
            #line default
            #line hidden
            
            #line 66 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                         Write(Model.varName);

            
            #line default
            #line hidden
            
            #line 66 "..\..\SqlTemplate\mysql\QueryAll.cshtml"
                                            
            
            #line default
            #line hidden
WriteLiteral("_command__.Dispose();\r\n\t#endregion\r\n\t\t\t");

        }
    }
}
#pragma warning restore 1591
